#Window State Configuration
#Sat Mar 28 18:38:47 GMT+05:00 2026
GAME_WINDOW.height=425
GAME_WINDOW.isClosed=false
GAME_WINDOW.width=656
GAME_WINDOW.x=677
GAME_WINDOW.y=88
LOG_WINDOW.height=490
LOG_WINDOW.isClosed=false
LOG_WINDOW.width=615
LOG_WINDOW.x=45
LOG_WINDOW.y=86
