#Window State Configuration
#Fri Apr 03 00:46:50 GMT+05:00 2026
GAME_WINDOW.height=770
GAME_WINDOW.isClosed=false
GAME_WINDOW.width=1536
GAME_WINDOW.x=0
GAME_WINDOW.y=0
LOG_WINDOW.height=490
LOG_WINDOW.isClosed=true
LOG_WINDOW.width=615
LOG_WINDOW.x=319
LOG_WINDOW.y=130
