#Window State Configuration
#Fri Mar 27 19:22:37 GMT+05:00 2026
GAME_WINDOW.height=408
GAME_WINDOW.isClosed=false
GAME_WINDOW.width=587
GAME_WINDOW.x=563
GAME_WINDOW.y=106
LOG_WINDOW.height=239
LOG_WINDOW.isClosed=false
LOG_WINDOW.width=342
LOG_WINDOW.x=61
LOG_WINDOW.y=114
